/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class EjercicioTest2 extends AnyFunSuite {
  val obj = new Ejercicio()
  test("Sum of numbers test 1") {
    assert(obj.sumOfNumbers(3) === 2)
  }

  test("Sum of numbers test 2") {
    assert(obj.sumOfNumbers(5) === 6)
  }

  test("Sum of numbers test 3") {
    assert(obj.sumOfNumbers(6) === 12)
  }

  test("Sum of numbers test 4") {
    assert(obj.sumOfNumbers(-2) === 0)
  }
}
