/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class EjercicioTest1 extends AnyFunSuite {
  val obj = new Ejercicio()
  test("Sum of squares test 1") {
    assert(obj.sumOfSquares(3) === 14)
  }

  test("Sum of squares test 2") {
    assert(obj.sumOfSquares(5) === 55)
  }

  test("Sum of power test 3") {
    assert(obj.sumOfSquares(6) === 91)
  }

  test("Sum of power test 4") {
    assert(obj.sumOfSquares(-2) === 0)
  }
}
